### ISSUE TITLE
"npx arkit src/ -o arkit.svg " gives npm ERR! errno -4048

### ISSUE THREAD

**Issue by greenstevester** [dyatko/arkit#127]
npx arkit src/ -o arkit.svg on Windows 10 results in

C:\javasource\ngx-datatable-master>npx arkit src/ -o arkit.svg
npm ERR! path C:\dev\npm-cache-current\_npx\2900\node_modules\arkit\node_modules\base\package.json.3809823343
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\dev\npm-cache-current\_npx\2900\node_modules\arkit\node_modules\base\package.json.3809823343' -> 'C:\dev\npm-cache-current\_npx\2900\node_modules\arkit\node_modules\base\package.json'
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\dev\npm-cache-current\_npx\2900\node_modules\arkit\node_modules\base\package.json.3809823343' -> 'C:\dev\npm-cache-current\_npx\2900\node_modules\arkit\node_modules\base\package.json']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, rename 'C:\dev\npm-cache-current\_npx\2900\node_modules\arkit\node_modules\base\package.json.3809823343' -> 'C:\dev\npm-cache-current\_npx\2900\node_modules\arkit\node_modules\base\package.json'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'rename',
npm ERR!      path:
npm ERR!       'C:\\dev\\npm-cache-current\\_npx\\2900\\node_modules\\arkit\\node_modules\\base\\package.json.3809823343',
npm ERR!      dest:
npm ERR!       'C:\\dev\\npm-cache-current\\_npx\\2900\\node_modules\\arkit\\node_modules\\base\\package.json' },
npm ERR!   stack:
npm ERR!    "Error: EPERM: operation not permitted, rename 'C:\\dev\\npm-cache-current\\_npx\\2900\\node_modules\\arkit\\node_modules\\base\\package.json.3809823343' -> 'C:\\dev\\npm-cache-current\\_npx\\2900\\node_modules\\arkit\\node_modules\\base\\package.json'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path:
npm ERR!    'C:\\dev\\npm-cache-current\\_npx\\2900\\node_modules\\arkit\\node_modules\\base\\package.json.3809823343',
npm ERR!   dest:
npm ERR!    'C:\\dev\\npm-cache-current\\_npx\\2900\\node_modules\\arkit\\node_modules\\base\\package.json',
npm ERR!   parent: 'arkit' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\dev\npm-cache-current\_logs\2019-08-05T09_54_42_228Z-debug.log
Install for arkit@latest failed with code 4294963248

**Comment by dyatko** [comment]
@greenstevester it's some npm/windows problem
Please try https://stackoverflow.com/a/45840283

**Comment by greenstevester** [comment]
npm cache clean --force solved the issue

**Comment by greenstevester** [comment]
@dyatko - thanks for the quick feedback
