### ISSUE TITLE
502 Bad gateway 

### ISSUE THREAD

**Issue by genesiscz** [dyatko/arkit#296]
I am getting 502 gateway in my arkit.svg file

**To Reproduce**
1. Operating system
Windows 10
2. Arkit version and CLI arguments
1.6.2
npx arkit src/ -o arkit.svg

3. Arkit config, if any was used
The arkit said me this was used
```
{
  "components": [
    {
      "type": "Dependency",
      "patterns": [
        "node_modules/*"
      ]
    },
    {
      "type": "Component",
      "patterns": [
        "**/*.ts",
        "**/*.js",
        "**/*.jsx",
        "**/*.tsx"
      ]
    },
    {
      "type": "Vue",
      "format": "full",
      "patterns": [
        "**/*.vue"
      ]
    }
  ],
  "excludePatterns": [
    "..\\test",
    "..\\tests",
    "..\\dist",
    "..\\coverage",
    "..\\**\\*.test.*",
    "..\\**\\*.spec.*",
    "..\\**\\*.min.*"
  ],
  "output": [
    {
      "path": [
        "..\\arkit.svg"
      ],
      "groups": [
        {
          "first": true,
          "components": [
            "Component",
            "Vue"
          ]
        },
        {
          "type": "Dependencies",
          "components": [
            "Dependency"
          ]
        }
      ]
    }
  ]
}
```

4. Source code example, if it's possible
just running the command 

arkit.svg contains:
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>
```

**Comment by rodmax** [comment]
i had the same issue yesterday

it seems the problem in service which described in README as 

> Arkit is using a web service to convert PlantUML to SVG/PNG. It's hosted at arkit.pro and does not store any data.....

**Comment by dyatko** [comment]
@rodmax @genesiscz Sorry guys, AWS machine decided to die after one year being stable. I've created a new one and now it should work smoothly. Sorry for the hiccup!
