### ISSUE TITLE
Object.values is not a function

### ISSUE THREAD

**Issue by kordashvg** [dyatko/arkit#31]
Bug description
Object.values is not a function

**To Reproduce**
1. Windows 10
2. 1.3.17 npx arkit src/ -o arkit.svg
3. --
4. `onStateChanged(evt) {
    const isEmpty = value => value === '';
    const isReset = isEmpty(evt.target.value);
    const user = { ...this.state.user, [evt.target.id]: evt.target.value };
    const isFormComplete = !isReset && !Object.values(user).some(isEmpty);
    this.setState({ user, isFormComplete });
  }`

**Comment by dyatko** [comment]
@kordashvg I've added these lines to test case but couldn't reproduce it. https://github.com/dyatko/arkit/commit/456711a408e6a239ad37d1aa4832717fef440291

Which Node.js version are you running?

**Comment by kordashvg** [comment]
6.11.3

**Comment by dyatko** [comment]
@kordashvg yeah, unfortunately, arkit is not aimed to support Node 6.x due to its expiration in April:

<img src="https://raw.githubusercontent.com/nodejs/Release/master/schedule.svg?sanitize=true" />
