### ISSUE TITLE
Allow CLI option to explicitly provide config path

### ISSUE THREAD

**Issue by mvanderkamp** [dyatko/arkit#45]
**Is your feature request related to a problem?**
The graphs produced by this package have really helped me organize a larger project I'm working on. There are many different groups of components in the system though, and I would like to be able to generate graphs for each group, by itself, as well as for the system as a whole. If there were a command line option to specify a config file, I would be able to save a config file for each group that I want a graph for, then just provide the appropriate filename when calling `arkit`.

**Describe the solution you'd like**
Just a simple command line option that allows config file specification instead of just assuming `arkit.json` or the contents of `package.json`.

**Describe alternatives you've considered**
Right now so far as I can tell this means I have to reach in and edit `arkit.json` every time.

**Comment by dyatko** [comment]
@mvanderkamp Hey Michael, thanks for the great feedback and idea!
Please enjoy arkit@1.5.0 with the config path option.

**Comment by mvanderkamp** [comment]
Works great! Thank you!
