### ISSUE TITLE
Opening and ending tag mismatch: meta line 0 and head

### ISSUE THREAD

**Issue by kordashvg** [dyatko/arkit#62]
Bug description

error on line 22 at column 11: Opening and ending tag mismatch: meta line 0 and head

1. Ubuntu 16.04
2. 1.3.17, -
3. `{
  "components": [
    {
      "type": "Entry",
      "patterns": [
        "src/*.js"
      ]
    },
    {
      "type": "Lib",
      "patterns": [
        "src/lib"
      ]
    },
    {
      "type": "Blockchain",
      "patterns": [
        "src/blockchain"
      ]
    },
    {
      "type": "Component",
      "patterns": [
        "src/**/*.js"
      ],
      "excludePatterns": [
        "**/__tests__/**",
        "**/*-test.js"
      ]
    }
  ],
  "excludePatterns": [
    "test",
    "tests",
    "dist",
    "coverage",
    "**/*.test.*",
    "**/*.spec.*",
    "**/*.min.*"
  ],
  "output": [
    {
      "path": [
        "arkit.svg"
      ],
      "groups": [
        {
          "first": true,
          "components": [
            "Entry"
          ],
          "patterns": [
            "src/index.js"
          ]
        },
        {
          "type": "Redux",
          "patterns": [
            "src/redux/**"
          ]
        },
        {
          "type": "Components",
          "patterns": [
            "src/components/**"
          ]
        },
        {
          "type": "Containers",
          "patterns": [
            "src/containers/**"
          ]
        },
        {
          "components": [
            "Component",
            "Entry",
            "Lib",
            "Blockchain"
          ]
        }
      ]
    }
  ]
}
`
4. -
![image](https://user-images.githubusercontent.com/38975659/55465040-0201ac00-5605-11e9-88ee-30d85976655d.png)

**Comment by dyatko** [comment]
@kordashvg Please install latest arkit@1.5.1

**Comment by kordashvg** [comment]
It Helped. Thank you
