### ISSUE TITLE
TypeScript: import types ignored

### ISSUE THREAD

**Issue by bobaaaaa** [dyatko/arkit#69]
Since TypeScript 2.9 there are [import-types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#import-types). At the moment arkit does not understand this kind of imports.

**To Reproduce**
1. OSX 10.14.3
2. 1.5.3

```ts
// types.ts
export interface Foo {}

// index.ts
type Foo = import('./types').Foo;

export class Bar {
  constructor(private foo: Foo) {}
}
```

**Comment by dyatko** [comment]
@bobaaaaa It's now supported in arkit@1.5.4, please give it a try
