### ISSUE TITLE
Allow NodeJS version >= 8.11

### ISSUE THREAD

**Issue by earshinov** [dyatko/arkit#81]
**Is your feature request related to a problem?**

We are currently using node 8.11 on developer machines and during CI.

arkit works perfectly under node 8.11, but requires >= 8.15 in package.json

Would be nice if arkit allowed 8.11 and we did not need to run yarn with --ignore-engines.

**Describe the solution you'd like**

In package.json, replace

```
"engines": {
  "node": ">= 8.15.0"
},
```

with

```
"engines": {
  "node": ">= 8.11.0"
},
```

**Describe alternatives you've considered**

—

**Comment by dyatko** [comment]
Allowed in 1.6.0
